export const GET_TRANSACTION_REQUEST = "GET_TRANSACTION_REQUEST"
export const GET_TRANSACTION_FAILURE = "GET_TRANSACTION_FAILURE"
export const GET_TRANSACTION_SUCCESS = "GET_TRANSACTION_SUCCESS"

export const GETTRANSACTIONSREQUEST = "GETTRANSACTIONSREQUEST";
export const GETTRANSACTIONSFAILURE = "GETTRANSACTIONSFAILURE";
export const GETTRANSACTIONSSUCCESS = "GETTRANSACTIONSSUCESS";