


export const GET_ADMIN_TRANSACTION_REQUEST = "GET_ADMIN_TRANSACTION_REQUEST"
export const GET_ADMIN_TRANSACTION_FAILURE = "GET_ADMIN_TRANSACTION_FAILURE"
export const GET_ADMIN_TRANSACTION_SUCCESS = "GET_ADMIN_TRANSACTION_SUCCESS"
export const GET_USERS_TRANSACTION_SUCCESS = "GET_USERS_TRANSACTION_SUCCESS"
export const GET_USERS_TRANSACTION_FAILURE = "GET_USERS_TRANSACTION_FAILURE"
export const GET_USERS_TRANSACTION_REQUEST = "GET_USERS_TRANSACTION_REQUEST"

