export const GETUSERSREQUEST = "GETUSERSREQUEST";
export const GETUSERSSUCCESS = "GETUSERSSUCCESS";
export const GETUSERSFAILURE = "GETUSERFAILURE";

export const PATCHUSERSREQUEST = "PATCHUSERSREQUEST";
export const PATCHUSERSSUCCESS = "PATCHUSERSSUCCESS";
export const PATCHUSERSFAILURE = "PATCHUSERFAILURE";