// support get and post
export const POST_QUERY_SUCCESS = "POST_QUERY_SUCCESS"
export const POST_QUERY_FAILURE = "POST_QUERY_FAILURE"
export const POST_QUERY_REQUEST = "POST_QUERY_REQUEST"
export const GET_SUPPORT_SUCCESS = "GET_SUPPORT_SUCCESS"
export const GET_SUPPORT_FAILURE = "GET_SUPPORT_FAILURE"
export const GET_SUPPORT_REQUEST = "GET_SUPPORT_REQUEST"