export const POSTLOGINREQUEST = "POSTLOGINREQUEST";
export const POSTLOGINSUCCESS = "POSTLOGINSUCCESS";
export const POSTLOGINFAIL = "POSTLOGINFAIL";
export const POSTADMINSUCESS= "POSTADMINSUCESS";
export const LOGOUT = "LOGOUT";
export const UPDATELOGGEDINUSER='UPDATELOGGEDINUSER';